
package vista;

import controlador.CPersona;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import modelo.Persona;

public class FrmLogin extends javax.swing.JFrame {
    
    
    public FrmLogin() {
        initComponents();
        this.setResizable(false);
        this.setSize(new Dimension(700,500));
        this.setLocationRelativeTo(null);
        this.setTitle("SISTEMA DE FINANZAS");
        
    }
    
    @Override
    public Image getIconImage(){
        Image img=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/icono2.png"));
        return img;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textoDNI = new javax.swing.JTextField();
        textoContrasenia = new javax.swing.JPasswordField();
        botonIniciarSesion = new javax.swing.JButton();
        botonCrearCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEMA DE FINANZAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel3.setText("DNI:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel4.setText("Contraseña:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        textoDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoDNIKeyPressed(evt);
            }
        });
        jPanel2.add(textoDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 250, -1));

        textoContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoContraseniaKeyPressed(evt);
            }
        });
        jPanel2.add(textoContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 250, -1));

        botonIniciarSesion.setBackground(new java.awt.Color(51, 153, 255));
        botonIniciarSesion.setText("Iniciar sesión");
        botonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(botonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        botonCrearCuenta.setBackground(new java.awt.Color(51, 153, 255));
        botonCrearCuenta.setText("Crear usuario");
        botonCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearCuentaActionPerformed(evt);
            }
        });
        jPanel2.add(botonCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 350, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed
        this.login();
    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    private void textoDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoDNIKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER){
            textoContrasenia.requestFocus();
        }
    }//GEN-LAST:event_textoDNIKeyPressed

    private void textoContraseniaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoContraseniaKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER){
            this.login();
        }
    }//GEN-LAST:event_textoContraseniaKeyPressed

    private void botonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearCuentaActionPerformed
        FrmNuevaPersona nPersona= new FrmNuevaPersona();
        nPersona.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_botonCrearCuentaActionPerformed

    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearCuenta;
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField textoContrasenia;
    private javax.swing.JTextField textoDNI;
    // End of variables declaration//GEN-END:variables
    private String convertir(char[]arr){
        String res="";
        for(int i=0;i<arr.length;i++){
            res+=arr[i];
        }
        return res;
    }
    private void login(){
        if(!textoDNI.getText().isEmpty()&&!convertir(textoContrasenia.getPassword()).equals("")){
            CPersona cP=new CPersona();
            Persona p=new Persona(textoDNI.getText(),convertir(textoContrasenia.getPassword()));
            Persona persona=cP.loginPersona(p);
            if(persona!=null){
                FrmMenu menu= new FrmMenu();
                menu.setPersona(persona);
                menu.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Usuario o clave incorrectos");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese sus credenciales");
        }
    }
}
