
package vista;

import controlador.CPersona;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import modelo.Persona;


public class FrmNuevaPersona extends javax.swing.JFrame {

    
    public FrmNuevaPersona() {
        initComponents();
        this.setResizable(false);
        this.setSize(new Dimension(300,500));
        this.setLocationRelativeTo(null);
        this.setTitle("Nuevo usuario");
        
    }
    @Override
    public Image getIconImage(){
        Image img=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/icono2.png"));
        return img;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoNombre = new javax.swing.JTextField();
        textoAp1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textoAp2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textoDNI = new javax.swing.JTextField();
        textoContrasenia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        botonNuevaPersona = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        textoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoNombreKeyPressed(evt);
            }
        });

        textoAp1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoAp1KeyPressed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Primer apellido");

        jLabel3.setText("Segundo apellido");

        textoAp2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoAp2KeyPressed(evt);
            }
        });

        jLabel4.setText("DNI:");

        textoDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoDNIKeyPressed(evt);
            }
        });

        textoContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoContraseniaKeyPressed(evt);
            }
        });

        jLabel5.setText("Contraseña:");

        botonNuevaPersona.setBackground(new java.awt.Color(51, 153, 255));
        botonNuevaPersona.setText("Crear Usuario");
        botonNuevaPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoContrasenia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(textoDNI, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoAp2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoAp1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botonNuevaPersona)
                        .addGap(23, 23, 23))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoAp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoAp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(botonNuevaPersona)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevaPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaPersonaActionPerformed
        this.creacionUsuario();
    }//GEN-LAST:event_botonNuevaPersonaActionPerformed

    private void textoNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNombreKeyPressed
       if(evt.getKeyCode()==evt.VK_ENTER){
            textoAp1.requestFocus();
        }
    }//GEN-LAST:event_textoNombreKeyPressed

    private void textoAp1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoAp1KeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER){
            textoAp2.requestFocus();
        }
    }//GEN-LAST:event_textoAp1KeyPressed

    private void textoAp2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoAp2KeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER){
            textoDNI.requestFocus();
        }
    }//GEN-LAST:event_textoAp2KeyPressed

    private void textoDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoDNIKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER){
            textoContrasenia.requestFocus();
        }
    }//GEN-LAST:event_textoDNIKeyPressed

    private void textoContraseniaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoContraseniaKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER){
            creacionUsuario();
        }
    }//GEN-LAST:event_textoContraseniaKeyPressed
    private boolean terminaLetra(char a){
        boolean res=false;
        if(a>=65&&a<=90){
            res=true;
        }
      
        return res;
    }
    private boolean esNumero(String num){
        boolean res=true;
        for(int i=0;i<num.length()&&res;i++){
            if(num.charAt(i)<48||num.charAt(i)>57){
                res=false;
            }
        }
        return res;
    }
    private void creacionUsuario(){
        if(!textoDNI.getText().isEmpty()&&!textoContrasenia.getText().isEmpty()&&!textoNombre.getText().isEmpty()&&!textoAp1.getText().isEmpty()&&!textoAp2.getText().isEmpty()){
            CPersona cP=new CPersona();
            if(textoDNI.getText().length()!=9||!terminaLetra(textoDNI.getText().charAt(textoDNI.getText().length()-1))||!esNumero(textoDNI.getText().substring(0, 7))){
                JOptionPane.showMessageDialog(null, "El DNI no tiene el formato correcto");
            }else{
                Persona p=new Persona(textoDNI.getText(),textoContrasenia.getText(), textoNombre.getText(),textoAp1.getText(),textoAp2.getText());
                if(cP.nuevaPersona(p)){
                FrmMenu menu= new FrmMenu();
                menu.setPersona(p);
                menu.setVisible(true);
                this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "El usuario ya está creado");
                }
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese sus credenciales");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNuevaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNuevaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNuevaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNuevaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNuevaPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonNuevaPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textoAp1;
    private javax.swing.JTextField textoAp2;
    private javax.swing.JTextField textoContrasenia;
    private javax.swing.JTextField textoDNI;
    private javax.swing.JTextField textoNombre;
    // End of variables declaration//GEN-END:variables
}
