
package vista;

import conexion.Conexion;
import modelo.Persona;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.*;


public class ListarIngresos extends javax.swing.JPanel  {
    public ListarIngresos() {
        initComponents();
        listarIngresos();
    }
    
    private void listarIngresos(){
        List<Ingreso>lista=cargaIngresos();
        DefaultTableModel model=new DefaultTableModel();
        ListarIngresos.tabla= new JTable(model);
        ListarIngresos.jScrollPane1.setViewportView(ListarIngresos.tabla);
        model.addColumn("Código");
        model.addColumn("Tipo");
        model.addColumn("Descripción");
        model.addColumn("Cantidad");
        model.addColumn("Fecha inicio");
        model.addColumn("Fecha fin");
        model.addColumn("Cuenta");
        for(Ingreso g:lista){
            Object fila[]= {g.getCodigo(),g.getTipo(),g.getDescripcion(),g.getDinero(),g.getFecha_inicio(),g.getFecha_fin(),g.getActivoFinanciero()};
            model.addRow(fila);
        }
        
    }
    private List<Ingreso> cargaIngresos(){
        List<Ingreso>lista=new ArrayList<>();
        Connection conn=Conexion.conectar();
        String sql="select * from ingreso where codigo_persona=? ;";
        PreparedStatement pst;
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1, FrmMenu.pers.getDni());
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
                Ingreso i=new Ingreso(rs.getString(2),rs.getString(3),rs.getDouble(4),rs.getDate(5).toLocalDate(),rs.getDate(6).toLocalDate(),rs.getString(7),rs.getInt(8));
                i.setCodigo(rs.getInt(1));
                lista.add(i);
            }
            conn.close();
        }catch(SQLException e){
            System.out.println(e);
        }
        return lista;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1077, 580));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1077, 580));
        jPanel1.setPreferredSize(new java.awt.Dimension(1077, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Lista de Ingresos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 370, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 710, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

   
}
