
package vista;

import conexion.Conexion;
import controlador.CGasto;
import java.sql.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import javax.swing.JOptionPane;
import modelo.*;

public class NuevoGastoOp extends javax.swing.JPanel {
    
    /**
     * Creates new form GastoOpciones
     */
    public NuevoGastoOp() {
        initComponents();
        listarCuenta();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtCoste = new javax.swing.JTextField();
        txtTipoDeGasto = new javax.swing.JTextField();
        txtFechaInicio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        txt_Cuenta = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setMinimumSize(new java.awt.Dimension(1077, 580));
        content.setPreferredSize(new java.awt.Dimension(1077, 580));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Nuevo gasto");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Descripción:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Cuenta:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Tipo de gasto:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Coste:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Fecha de inicio:");

        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyPressed(evt);
            }
        });

        txtCoste.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCosteKeyPressed(evt);
            }
        });

        txtTipoDeGasto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTipoDeGastoKeyPressed(evt);
            }
        });

        txtFechaInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaInicioKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Fecha fin:");

        txtFechaFin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaFinKeyPressed(evt);
            }
        });

        txt_Cuenta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Cuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenta", "Item 1", "Item 2", "Item 3", "Item 4" }));
        txt_Cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CuentaActionPerformed(evt);
            }
        });
        txt_Cuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_CuentaKeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gasto2.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTipoDeGasto))
                        .addGap(310, 310, 310)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(txtDescripcion)
                                .addGap(14, 14, 14))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(86, 86, 86))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(txtCoste)
                                .addGap(14, 14, 14))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(txtFechaInicio)
                                .addGap(14, 14, 14))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(53, 53, 53))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(txtFechaFin)
                                .addGap(14, 14, 14)))
                        .addGap(256, 256, 256)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(537, 537, 537))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(txt_Cuenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(500, 500, 500)))
                .addGap(317, 317, 317))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)
                        .addComponent(txtTipoDeGasto))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addGap(28, 28, 28)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)
                        .addComponent(txtDescripcion)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)
                        .addComponent(txtCoste)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)
                        .addComponent(txtFechaInicio)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)
                        .addComponent(txtFechaFin)
                        .addGap(8, 8, 8))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(txt_Cuenta)
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_CuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CuentaActionPerformed

    private void nuevoGasto(){
        String activoFinanciero="";
        activoFinanciero=txt_Cuenta.getSelectedItem().toString();
        if(!txtTipoDeGasto.getText().isEmpty()||!txtDescripcion.getText().isEmpty()||!txtCoste.getText().isEmpty()||!txtFechaInicio.getText().isEmpty()||!activoFinanciero.equals("")){
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            CGasto aux=new CGasto();
            Gasto gasto=new Gasto(txtTipoDeGasto.getText(),txtDescripcion.getText(),Double.parseDouble(txtCoste.getText()),LocalDate.parse(txtFechaInicio.getText(), formatter),LocalDate.parse(txtFechaFin.getText(), formatter),aux.claveCuenta(activoFinanciero),FrmMenu.pers.getDni());
            Cuenta cuenta=cuentaDescripcion(activoFinanciero);
            if(cuenta.getDinero()<Double.parseDouble(txtCoste.getText())){
                JOptionPane.showMessageDialog(null, "Saldo insuficiente en la cuenta" ); 
            }else{
                if(!aux.ingresarGasto(gasto)){
                   JOptionPane.showMessageDialog(null, "Fallo al crear el Gasto " );
                }else{
                    JOptionPane.showMessageDialog(null, "Se ha creado un gasto");
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Complete los campos");
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nuevoGasto();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void txtTipoDeGastoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoDeGastoKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER){
            txtDescripcion.requestFocus();
        }
    }//GEN-LAST:event_txtTipoDeGastoKeyPressed

    private void txtDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER){
            txtCoste.requestFocus();
        }
    }//GEN-LAST:event_txtDescripcionKeyPressed

    private void txtCosteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCosteKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER){
            txtFechaInicio.requestFocus();
        }
    }//GEN-LAST:event_txtCosteKeyPressed

    private void txtFechaInicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaInicioKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER){
            txtFechaFin.requestFocus();
        }
    }//GEN-LAST:event_txtFechaInicioKeyPressed

    private void txtFechaFinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaFinKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER){
            txt_Cuenta.requestFocus();
        }
    }//GEN-LAST:event_txtFechaFinKeyPressed

    private void txt_CuentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CuentaKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER){
            
        }
    }//GEN-LAST:event_txt_CuentaKeyPressed
    
    
    
   private Cuenta cuentaDescripcion(String s){
       Cuenta res=null;
       List<Cuenta>lista=cargaCuenta();
       for(int i=0;i<lista.size();i++){
           if(lista.get(i).getDescripcion().equals(s)){
               res=lista.get(i);
           }
       }
       return res;
   }
   private List<Cuenta> cargaCuenta(){
        List<Cuenta>lista=new ArrayList<>();
        Connection conn=Conexion.conectar();
        String sql="select af.* from cuenta af, cuenta_persona ap where ap.cod_persona= ? AND ap.cod_cuenta=af.codigo ;";
        PreparedStatement pst;
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1, FrmMenu.pers.getDni());
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
                lista.add(new Cuenta(rs.getInt(1),rs.getString(2),rs.getString(3),rs.getDouble(4)));
            }
            conn.close();
        }catch(SQLException e){
            System.out.println(e);
        }
        return lista;
    }
   
    private void listarCuenta(){
        List<Cuenta>lista=cargaCuenta();
        txt_Cuenta.removeAllItems();
        for(Cuenta a: lista){
            txt_Cuenta.addItem(a.getDescripcion());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCoste;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtTipoDeGasto;
    private javax.swing.JComboBox<String> txt_Cuenta;
    // End of variables declaration//GEN-END:variables
}
